version: '3.8'

services:
  # Base de données MySQL
  db:
    image: mysql:8.0
    container_name: ime-mysql-collabspace
    environment:
      MYSQL_DATABASE: collabspace
      MYSQL_USER: anne
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - collabspace-network

  # Backend Spring Boot
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: collabspace-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ime-mysql-collabspace:3306/collabspace?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: anne
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: kuitoange01@gmail.com
      SPRING_MAIL_PASSWORD: dubu gvps anbn tmbd
      SPRING_MAIL_PROTOCOL: smtp
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      JWT_SECRET_KEY: MaSuperCleSecretePourLeJWT1234567890!
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    restart: always
    networks:
      - collabspace-network

  # Frontend Nuxt
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: collabspace-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - collabspace-network

volumes:
  db_data:

networks:
  collabspace-network:
    driver: bridge 